<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJxsg4cd\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJxsg4cd/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerJxsg4cd.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerJxsg4cd\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerJxsg4cd\appProdProjectContainer(array(
    'container.build_hash' => 'Jxsg4cd',
    'container.build_id' => '909df143',
    'container.build_time' => 1538406582,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerJxsg4cd');
